import { z } from 'zod';

/**
 * Every rule's `config` column is `jsonb` at the schema level (see the
 * migration), but nothing in this codebase ever treats that JSON as
 * executable without first validating it against one of these schemas,
 * keyed on `trigger_type`. An unvalidated/malformed config is a rejected
 * write or a skipped evaluation — never a crash, and never arbitrary code
 * execution.
 *
 * `response_threshold` is the only trigger type implemented in Phase 5 —
 * see the "five distinct people respond" example from the product spec.
 * The schema is deliberately extensible (new trigger types add new zod
 * schemas and extend `RuleConfigSchema`'s union) without touching the rule
 * engine's own control flow.
 */
export const QualifyConfigSchema = z.object({
  /**
   * 'contains': text includes the phrase anywhere (case-insensitive).
   * 'exact': text, trimmed, equals the phrase exactly (case-insensitive).
   * 'keyword_any': any whitespace-delimited word in the text matches a
   * phrase exactly (case-insensitive) — stricter than 'contains', looser
   * than 'exact'.
   */
  mode: z.enum(['contains', 'exact', 'keyword_any']),
  /** Case-insensitive; matched against after trimming. At least one required. */
  phrases: z.array(z.string().trim().min(1)).min(1).max(50),
});
export type QualifyConfig = z.infer<typeof QualifyConfigSchema>;

export const ActionConfigSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('SEND_MESSAGE'), message: z.string().trim().min(1).max(4096) }),
  z.object({ type: z.literal('NOTIFY_OWNER'), message: z.string().trim().min(1).max(4096) }),
  z.object({ type: z.literal('LOG_ONLY') }),
]);
export type ActionConfig = z.infer<typeof ActionConfigSchema>;

export const ResponseThresholdConfigSchema = z.object({
  /**
   * How the "target message" is identified. 'quoted' is the only mode
   * implemented: a qualifying response must be a reply/quote of the
   * announcement — see docs/DECISIONS.md ADR-012 and product spec #12.
   */
  targetMessageMatch: z.literal('quoted'),
  qualify: QualifyConfigSchema,
  /** Number of DISTINCT qualifying senders required to fire. */
  threshold: z.number().int().min(1).max(10_000),
  action: ActionConfigSchema,
  /** Minimum seconds between this rule firing again. 0 = no cooldown. */
  cooldownSeconds: z.number().int().min(0).max(86_400).default(0),
});
export type ResponseThresholdConfig = z.infer<typeof ResponseThresholdConfigSchema>;

/**
 * `auto_reply` (Phase 6+): fires immediately on each qualifying message —
 * no threshold/distinct-sender tracking, unlike `response_threshold`. The
 * owner must configure WHEN it responds (product spec Part B) — qualify
 * is still either deterministic keyword matching or, explicitly opted
 * into per rule, AI semantic classification. AI-powered auto-reply
 * additionally requires THREE separate group-level gates to all be true
 * (`ai_enabled`, `auto_reply_enabled`, `ai_auto_reply_enabled`) — see
 * src/rules/ruleEngine.ts's `evaluateAutoReply()` — this schema only
 * captures what the rule itself asks for, not whether it's currently
 * permitted.
 */
export const AutoReplyQualifyConfigSchema = z.discriminatedUnion('classifier', [
  z.object({
    classifier: z.literal('deterministic'),
    mode: z.enum(['contains', 'exact', 'keyword_any']),
    phrases: z.array(z.string().trim().min(1)).min(1).max(50),
  }),
  z.object({
    classifier: z.literal('ai'),
    /** Plain-language description of what qualifies — e.g. "asks about opening hours". */
    aiInstructions: z.string().trim().min(1).max(500),
  }),
]);
export type AutoReplyQualifyConfig = z.infer<typeof AutoReplyQualifyConfigSchema>;

export const AutoReplyActionConfigSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('SEND_MESSAGE'), message: z.string().trim().min(1).max(4096) }),
  /** The reply text is generated by AI at evaluation time — requires the same AI gates as the qualify classifier. */
  z.object({ type: z.literal('AI_REPLY') }),
]);
export type AutoReplyActionConfig = z.infer<typeof AutoReplyActionConfigSchema>;

export const AutoReplyConfigSchema = z.object({
  qualify: AutoReplyQualifyConfigSchema,
  action: AutoReplyActionConfigSchema,
  cooldownSeconds: z.number().int().min(0).max(86_400).default(0),
});
export type AutoReplyConfig = z.infer<typeof AutoReplyConfigSchema>;

/**
 * `moderation` (Phase 6+): deterministic-only (no AI classifier — product
 * spec Part G says "start with deterministic moderation" and does not ask
 * for AI moderation in this phase). `DELETE_MESSAGE`/`REMOVE_USER` are
 * validated here as acceptable *shapes*, but the rule engine additionally
 * requires `group_settings.moderation_destructive_actions_enabled` before
 * actually executing either — "never silently remove people" (spec).
 */
export const ModerationQualifyConfigSchema = z.object({
  bannedPhrases: z.array(z.string().trim().min(1)).max(200).default([]),
  /** 0 = disabled. Same sender sending >= this many messages within spamWindowSeconds qualifies as spam. */
  spamRepeatThreshold: z.number().int().min(0).max(100).default(0),
  spamWindowSeconds: z.number().int().min(1).max(3600).default(30),
  detectLinks: z.boolean().default(false),
});
export type ModerationQualifyConfig = z.infer<typeof ModerationQualifyConfigSchema>;

export const ModerationActionConfigSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('LOG_ONLY') }),
  z.object({ type: z.literal('WARN'), message: z.string().trim().min(1).max(1000) }),
  z.object({ type: z.literal('NOTIFY_OWNER'), message: z.string().trim().min(1).max(1000) }),
  z.object({ type: z.literal('DELETE_MESSAGE') }),
  z.object({ type: z.literal('REMOVE_USER') }),
]);
export type ModerationActionConfig = z.infer<typeof ModerationActionConfigSchema>;

export const ModerationConfigSchema = z.object({
  qualify: ModerationQualifyConfigSchema,
  action: ModerationActionConfigSchema,
  cooldownSeconds: z.number().int().min(0).max(86_400).default(0),
});
export type ModerationConfig = z.infer<typeof ModerationConfigSchema>;

/**
 * `escalation` (Phase 8): deterministic-only phrase matching (same shape
 * as `response_threshold`'s qualify) for urgent/sensitive intents (refund,
 * complaint, legal, emergency, ...) that should reach the owner instead of
 * being auto-replied to. `category` is a free-text label the owner picks
 * (e.g. "refund") — it both documents intent and becomes the Owner Inbox
 * item's tag, so no separate "tag" mechanism is needed. Works for both
 * groups and private contacts (unlike moderation, which is group-only).
 */
export const EscalationActionConfigSchema = z.object({
  category: z.string().trim().min(1).max(50),
  notifyOwner: z.boolean().default(true),
  createInboxItem: z.boolean().default(true),
  /** Suppresses every auto_reply rule for THIS message only (not a standing override — see neverAutoReply for that). */
  suppressAutoReply: z.boolean().default(true),
});
export type EscalationActionConfig = z.infer<typeof EscalationActionConfigSchema>;

export const EscalationConfigSchema = z.object({
  qualify: QualifyConfigSchema,
  action: EscalationActionConfigSchema,
  cooldownSeconds: z.number().int().min(0).max(86_400).default(0),
});
export type EscalationConfig = z.infer<typeof EscalationConfigSchema>;

export type GroupRuleConfig =
  ResponseThresholdConfig | AutoReplyConfig | ModerationConfig | EscalationConfig;

export const TRIGGER_TYPES = [
  'response_threshold',
  'auto_reply',
  'moderation',
  'escalation',
] as const;
export type TriggerType = (typeof TRIGGER_TYPES)[number];

const SCHEMAS_BY_TRIGGER_TYPE: Record<TriggerType, z.ZodType> = {
  response_threshold: ResponseThresholdConfigSchema,
  auto_reply: AutoReplyConfigSchema,
  moderation: ModerationConfigSchema,
  escalation: EscalationConfigSchema,
};

/**
 * Validates a rule's `config` against the schema for its `trigger_type`.
 * Throws a descriptive error (never silently coerces) on anything invalid
 * — this is the one gate every write and every execution path must pass
 * through. See src/db/rulesRepository.ts and src/rules/ruleEngine.ts.
 */
export function validateRuleConfig(triggerType: string, config: unknown): GroupRuleConfig {
  const schema = SCHEMAS_BY_TRIGGER_TYPE[triggerType as TriggerType];
  if (!schema) {
    throw new Error(
      `Unknown rule trigger_type "${triggerType}" — must be one of: ${TRIGGER_TYPES.join(', ')}`,
    );
  }
  const result = schema.safeParse(config);
  if (!result.success) {
    const issues = result.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    throw new Error(`Invalid rule config for trigger_type "${triggerType}": ${issues}`);
  }
  return result.data as GroupRuleConfig;
}
